export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_USER = "UPDATE_USER";
export const LOADING = "LOADING";
export const ENABLE_FLASH_MESSAGE = "ENABLE_FLASH_MESSAGE";
export const DISABLE_FLASH_MESSAGE = "DISABLE_FLASH_MESSAGE";
